### PR TITLE
CopterHack2023 team homelesses

### PR DESCRIPTION
**Pull request by Isa-jesus**

### CODE REVIEW

**Comment by SeliverstovaE** [comment]
Dear friend,

Thank you for your interest in the CopterHack 2023 contest. Your application has successfully passed the experts’ review and was accepted for the second project stage of the competition, which will be held until February 28, 2023. This stage will be followed by monthly updates, lectures, and guidance from industry experts.

What's next?

1. Join the Telegram group with participants of the second project stage “[CopterHack 2023, participants chat](https://t.me/+t8hLtf-w2EwzOWM6)”.  
2. Every month, you're expected to prepare free-form reports on the progress of your project (update) in this draft pull request. In your report please indicate your progress, what tasks have been solved. You are encouraged to attach photos and videos that demonstrate the results of the work done within the month.
3. Send the link to the update to the participants chat in the Telegram group.

In response to the message, you will receive feedback from the competition jury.

There is no specific date for sending the report, so you can send the report between the beginning and the end of the month.

Monthly updates become mandatory from November 2022.

We are interested in helping you to complete your project as much as possible by the final stage. We wish you success!

Always in touch! Your CopterHack team.

**Comment by Isa-jesus** [comment]
November update
Was planned:

- Test abilities of a copter
- Make some tests with bottles
- Make a prototype of the system to catch botlles 

Problems:

- The copter can not lift up heavy bottles
- The copter can not catch light bottles

Solutions:

- We dicided to change our theme from "trash-collector" to "show_maker" 

Results:

- We made some prototypes and challanged one of them:
photo_2022-11-30_21-00-47
photo_2022-11-30_21-00-55
photo_2022-11-30_21-01-20

https://user-images.githubusercontent.com/116718375/204832838-ce453c07-c0bb-49f3-af34-f7d86706e428.MOV

Plans for December:

- Make a platform for the copter
- Make working prototypes 
- Make some universal fasteners for the copter to fasten some objects

**Comment by Isa-jesus** [comment]
December update
Was planned:

* Make a platform for the copter
* Make working prototypes
* Make some universal fasteners for the copter to fasten some objects

Problems:

The copter can not land with objects 

Solutions:

We made a platform where the copter lands

Results:

The platform:

 It is strong enough, so the drone can land on it without any problems.

image

The drone will land on the platform with the flag:

image


https://user-images.githubusercontent.com/116718375/210133482-d67e1097-a62c-4120-93dc-081ac79deedc.MOV

We made 3D models of the fasteners to print them on the 3D printer:

1st variant: 

fastener 01

This model was too big and wasteful, so we ramade it.

2nd variant:


fastener 02

Explanation:

https://drive.google.com/drive/folders/13BCCKFnrGdJqRaQ-vJI8blEkWxfr6s2v?usp=sharing

Plans for January:

* Print the fasteners
* Test the platform
* Test how the drone flies with the flag

**Comment by Isa-jesus** [comment]
January update

Was planned:

Print the fasteners
Test the platform
Test how the drone flies with the flag

Done work:

We printed some 3D models to connect our copter and flag. Now we can connect them easily and fast:
image
image
image

We checked the platform, if it's strong enough for the copter and flag, how the drone lands on it and takes off.
The platform works perfectly.

Also we checked if the drone can fly with flag and with the A2 paper.

Problems:

It flies with the A2 paper, but really badly. It's not stable and it's hard to control the copter.
The copter cannot fly with the flag. Our flag and other objects which connects them are too heavy for our drone.

Plans:

Reconstruct the system of connecting the drone with our flag and other objects. (Make it easier)
Print new flag which will be easy enough for the drone to fly.

**Pull request closed without merging**
