### PR TITLE
Drone hawk security

### PR DESCRIPTION
**Pull request by slavaroot**

### CODE REVIEW

**Comment by slavaroot** [comment]
###  DONE. DECEMBER

Launched a red mark detection node on my quadcopter with Raspberry. Further, based on this code, instead of a HSV filter, i will use YOLO v4 will be used to detect different drone models in motion instead of a red mark and will be published to the Following node.

**Detection node**

Allows you to detect the red mark attached to the drone and published the coordinates to the topic.

1. Get the image from the camera.
2. Convert the video stream from the camera into hsv.
3. Fllter by the desired range hue, saturation, value, using cv2.inRange.
4. Invert the image to be able to filter everything except the mark.
5. Get the filter and find the label on the filter image using the contour selection function cv2.findContours.
6. Go through all the found contours, select those that are more than 10x10 points, and select the largest of them - this will be the label.
7. Based on the image from the camera, the program calculates the distance to the mark and the yaw and pitch angles by which the mark deviates from the center of the camera image.
8. Publish the coordinates of the label in the corresponding ROS topics / label_detector / twist

Based on the code of user copterspace from github adapted for python3 noetic and bug fixes.


[Demonstration of the Detection node]( https://youtu.be/U8YqGskSH-U) 

**Following node**

Receives the coordinates of the red mark and moves the drone.

1. The drone's velocity vector is controlled by information about the position of the red label, obtained from the topic / baloon_detector / twist
2. Send a message about controlling the speed of the drone to the topic / mavros / setpoint_velocity / cmd_vel_unstamped
3. For the speed of movement forward (relative to the drone), track the current position (pose) of the drone


[Link to all code]( https://github.com/slavaroot/dh-)


###  TO DO. JANUARY 2022

- [ ] 1. Test the Following node in real
- [ ] 2. Replace the hsv filter with YOLO v4 algorithm

**Comment by slavaroot** [comment]
### DONE. JANUARY

1. YOLO4 neural network is configured.
2. A trained dataset was found to detect different models of drones.
3. Tested the detection of drones on photos and videos in different conditions and different models of drones. High accuracy obtained (See example in Result).


### Result

[Process video](https://youtu.be/jsu872-RxJw)

[Video 1 result](https://www.youtube.com/watch?v=pFbzr1ZZYbw)

[Video 2 result](https://www.youtube.com/watch?v=MG_gk65W-5c)


You can try the model in my  [Google Colab](https://colab.research.google.com/drive/18tKZN7RkOEkEsJuDFXeOjgkYs5xPDrDx?usp=sharing)

**Important! Need to load weights from Github**

### TO DO. FEBRUARY

1. Run YOLO4 on Raspberry.
2. Connect Following node and YOLO4 neural network.
3. Test all the code on the drone in real.

**Comment by slavaroot** [comment]
FEBRUARY

-Developing a YOLOv4 package for ROS Noetic;
-Trying to run https://github.com/slavaroot/darknet_ros on Raspberry;

PLANS. MARCH
- Modify and run the YOLOv4 package;
- Connect Following node with YOLOv4 package.

**Comment by SeliverstovaE** [comment]
Dear R.S. team,
We are closing pull request for your project as you didn’t get to the final round of the competition. 

You are welcome to submit your article to the clover documentation as an clover platform-based project. In order to do this please create a new pull request or make a comment to the existing one.

We wish you success in implementing your project and invite you to the next events.

**Pull request closed without merging**
