### PR TITLE
DJS PHOENIX

### PR DESCRIPTION
**Pull request by DJSPhoenix**

### CODE REVIEW

**Comment by SeliverstovaE** [comment]
Dear friend,

Thank you for your interest in the CopterHack 2023 contest. Your application has successfully passed the experts’ review and was accepted for the second project stage of the competition, which will be held until February 28, 2023. This stage will be followed by monthly updates, lectures, and guidance from industry experts.

What's next?

1. Join the Telegram group with participants of the second project stage “[CopterHack 2023, participants chat](https://t.me/+t8hLtf-w2EwzOWM6)”.  
2. Every month, you're expected to prepare free-form reports on the progress of your project (update) in this draft pull request. In your report please indicate your progress, what tasks have been solved. You are encouraged to attach photos and videos that demonstrate the results of the work done within the month.
3. Send the link to the update to the participants chat in the Telegram group.

In response to the message, you will receive feedback from the competition jury.

There is no specific date for sending the report, so you can send the report between the beginning and the end of the month.

Monthly updates become mandatory from November 2022.

We are interested in helping you to complete your project as much as possible by the final stage. We wish you success!

Always in touch! Your CopterHack team.

**Comment by DJSPhoenix** [comment]
#462 
Update for the month of #November #DJSPhoenix

TASKS FOR NOVEMBER
1. For the first month we are going to make a basic CAD model so that we can get a rough idea about the requirements and components to be bought.

2. Planned about how to proceed further in Coding. Learning the new concept of ROS, Keras Model.

3. Selection Of Components

- [ ]  LIST OF TASK COMPLETED FOR NOVEMBER

- [x] Basic CAD model is done with placement of components. The file of CAD model is attached below.

- [x] Thorough research regarding all the components which will be required for an autonomous racing drone was done. The components list was finalised . 

- [x] Brushed Up the concept of ROS and learnt about the Keras model. Brainstormed with the team members about the execution and assigned various tasks was done.

- [x] Selection of main components has been done and order is placed since coming from different countries it  will be delivered  in month of December.

- [x] The selected components are as follows:

  1. Flight Controller- F4 Fc STM32F405 RGT6 based flight controller

  2. Frame - carbon fiber x frame
  3. Electronic Speed Controller – 35 amps support MULTISHOT, ONESHOT42, ONESHOT125 calibration protocol.

  4. Motors- 2207 2300kv

  5. Propellers- 5” props

  6. Camera- The baseboard of the camera has three on-board cameras which implement stereo and RGB vision, for depth and AI processing. 

  7. Raspberry Pi 4
  8. LIDAR -VL53LOX
  9. Battery-4s 2500mah

DIFFICULTIES FACED

 1. Selection of components was a tedious task as we are making Autonomous Racing Drone and the budget is the constraint factor.  

2. Applying the knowledge of reinforcement learning.

3. First Deep learning project so little bit of time is consumed  to understand the things.

FUTURE PLANS
1. All the packages and models which are to make will be published in GitHub next month onwards.

2. Will start  building drone and the manual takeoff of drone will be done in the next update.

3. Will create BOM as soon as the shipment takes place.

CAD FILES

[CadFiles.zip](https://github.com/CopterExpress/clover/files/10114455/CadFiles.zip)

**Comment by DJSPhoenix** [comment]
TASK:
1.	Frame durability testing.
2.	Train the neural network to detect gates.
3.	Create Bill of Materials (BOM).
4.	3D Print CAD models for casing using PLA and TPU.

COMPLETITION OF TASK:
- [x]	Durability test has been conducted successfully.
- [x]	Detection and training of the neural network has been completed and the code for it has been uploaded on our GitHub repository.
- [x]	Documentation for the neural network and the source code has been created.

PROBLEMS:
1.	Shipment was delayed for around 10 days thus took time to make manual drone.
2.	The final amount was little higher than the expected amount so being a student committee gathering funds was a tedious task.
3.	To debug the code of neural network ,training was done correctly yet while testing gates were not detected , and a mistake in code was later noted although the to debugging of that mistake took us several days. 

CHALLENGES:
If the camera detects out multiple gates at a same time so where will the drone go?

SOLUTION:
We saw an open-source project and there they had attached ArUco markers on the gates. If multiple gates are detected, the drone will go to the gate which has the ArUco, whose ID precedes the other. So, we have taken the reference of the open source project  and gone through how they have achieved this task and implemented the code and it is working good for our project.

PLANS FOR JANUARY:
1.	Integration of gate detection with the AI camera and making of the node file.
2.	Simulation of gates along with ArUco markers to solve the problem of multiple gate detection.

REFERENCES:
1. https://github.com/atom-robotics-lab/aruco_navigation

All the videos and documentation mentioned above is uploaded in the zip file.
[Videos_Bom.zip](https://github.com/CopterExpress/clover/files/10326866/Videos_Bom.zip)

Github repo link for Gate Detection:
https://github.com/DJSPhoenix/GatesDetection

**Comment by DJSPhoenix** [comment]
Update for the month of #January  #DjsPhoenix

TASK :
1. Simulation of the autonomous racing drone.

COMPLETION OF TASK:
Partially Completed and the code has been published on our Github rep. Link for the same has been provided below.
https://github.com/DJSPhoenix/aruconavigation_simulation

Difficulties Faced:
1.  We are undergraduate students and we had our final exams thus we were not able to complete our task.

Plans for February
1. Simulation of our drone by performing the task.
2. Working on the actual drone.

**Comment by Cryptoknight1410** [comment]
Update for the month of #February #DjsPhoenix
Task:
Simulation of our project and hovering of Manual drone .

Completion of Task:
It's partially complete, detection of ArUco tags is done successfully. Some changes in the code are to be done, as the flight is not stable and drone is not passing through the gates as required. 

And for the manual drone the video has been provided. It's hovering for the certain period of time and then drone is going up and down. 

Both the simulation and real-world video has been provided below. 

March Month task:
Making the drone autonomous and fixing the simulation code.


https://drive.google.com/drive/folders/1Nes_zYZMRhvrMOMJJc-Q4qSs4lcPceYR?usp=sharing

**Comment by DJSPhoenix** [comment]
Update for the month of #February #DjsPhoenix
Task:
Simulation of our project and hovering of Manual drone .

Completion of Task:
It's partially complete, detection of ArUco tags is done successfully. Some changes in the code are to be done, as the flight is not stable and drone is not passing through the gates as required.

And for the manual drone the video has been provided. It's hovering for the certain period of time and then drone is going up and down.

Both the simulation and real-world video has been provided below.

March Month task:
Making the drone autonomous and fixing the simulation code.

https://drive.google.com/drive/folders/1Nes_zYZMRhvrMOMJJc-Q4qSs4lcPceYR?usp=sharing

**Comment by okalachev** [comment]
Performed some editing of you article, now it's ready to be merged.

**Pull request merged**
