### PR TITLE
Copterhack 2023: Drone-interceptor

### PR DESCRIPTION
**Pull request by deadln**

### CODE REVIEW

**Comment by SeliverstovaE** [comment]
Dear friend,

Thank you for your interest in the CopterHack 2023 contest. Your application has successfully passed the experts’ review and was accepted for the second project stage of the competition, which will be held until February 28, 2023. This stage will be followed by monthly updates, lectures, and guidance from industry experts.

What's next?

1. Join the Telegram group with participants of the second project stage “[CopterHack 2023, participants chat](https://t.me/+t8hLtf-w2EwzOWM6)”.  
2. Every month, you're expected to prepare free-form reports on the progress of your project (update) in this draft pull request. In your report please indicate your progress, what tasks have been solved. You are encouraged to attach photos and videos that demonstrate the results of the work done within the month.
3. Send the link to the update to the participants chat in the Telegram group.

In response to the message, you will receive feedback from the competition jury.

There is no specific date for sending the report, so you can send the report between the beginning and the end of the month.

Monthly updates become mandatory from November 2022.

We are interested in helping you to complete your project as much as possible by the final stage. We wish you success!

Always in touch! Your CopterHack team.

**Comment by deadln** [comment]
# November 2022 update

## Tasks

1. Assemble the interceptor.
2. Recover interceptor software.
3. Test software subsystems "on the ground".
4. Test interceptor in RC flight.
5. Test interceptor in autonomous flight.

## Solutions

1. I assembled my interceptor relatively quickly because I made many photos and schemata during the work on my bachelor thesis.
2. Since the initial process of creating the interceptor all code base and system image on SD card were untouched.
3. I launched processes of my systems separatly and checked their work using debug outputs.
4. I used indoor flight zone of my university to check the flight of my interceptor using RC.
5. This task wasn't complete.

## Challenges

1. During the assembly I accidently broke wires of my weight sensor, so i had to solder them again.
2. Suddenly, my neural network(my own fork of YOLOv5) refused to work due to missing libraries in the virtual environment. Reinstallation of libraries didn't help. In the end I updated my fork of YOLOv5 to the newer version and implemented my changes for it.
3. Every subsystem worked fine. But the target detection neural network had low rate of detection during the tests in workshop. That means i probably should train the neural network for new conditions.
4. During the flight i noticed atypical wobble of my front camera. I inspected my drone and noticed that the mounting deck which is used for Raspberry Pi installation is deformed. So i disassembled my copter and replaced the deck.
5. The flight zone of my university doesn't have aruco-markers.

## Plans for the next month

1. Cover the flight zone with aruco-markers.
2. Test autonomous flight of interceptor.
3. Train my neural network with new dataset if necessary.

**Comment by deadln** [comment]
# December 2022 update

## Tasks

1. Cover the flight zone with aruco-markers.
2. Search the existing solutions for outdoor visual navigation.
2. Test autonomous flight of interceptor.
3. Train my neural network with new dataset if necessary.

## Solutions

1. Little progress on the task.
2. Search for the open source projects.
3. Task has been postponed.
4. Task has been postponed.

## Challenges

Due to external circumstances, work on the project was significantly slowed down. As for the task 2, there is 
currently no existing open-source solutions that could be applied to project from-the-box. But I found few papers
about such methods that could be analyzed and performed into real solution.

## Plans for the next month

1. Finish covering the flight zone with aruco-markers.
2. Test autonomous flight of interceptor.
3. Train my neural network with new dataset if necessary.

**Comment by deadln** [comment]
# January 2023 update

## Tasks

1. Finish covering the flight zone with aruco-markers.
2. Test autonomous flight of interceptor.
3. Train my neural network with new dataset if necessary.

## Solutions

1. Complete
2. Didn't complete
3. Didn't complete

## Challenges

For the past two month there is two challenges that interrupt my work on this project: exams and sudden illnesses.

## Plans for the next month

Since I don't have much time to develop my project any further I will now concetrate on documentation of thing that's been already done. So I'm planning to begin to write the article for project.

**Comment by deadln** [comment]
# February 2023 final update

Due to lack of time and resources for developing my project to appropriate level I decided to abort my participation in Copterhack 2023.

**Pull request closed without merging**
