### PR TITLE
Create MoCap-Clover

### PR DESCRIPTION
**Pull request by ssmith-81**
CopterHack 2023 application

### CODE REVIEW

**Comment by SeliverstovaE** [comment]
Dear friend,

Thank you for your interest in the CopterHack 2023 contest. Your application has successfully passed the experts’ review and was accepted for the second project stage of the competition, which will be held until February 28, 2023. This stage will be followed by monthly updates, lectures, and guidance from industry experts.

What's next?

1. Join the Telegram group with participants of the second project stage “[CopterHack 2023, participants chat](https://t.me/+t8hLtf-w2EwzOWM6)”.  
2. Every month, you're expected to prepare free-form reports on the progress of your project (update) in this draft pull request. In your report please indicate your progress, what tasks have been solved. You are encouraged to attach photos and videos that demonstrate the results of the work done within the month.
3. Send the link to the update to the participants chat in the Telegram group.

In response to the message, you will receive feedback from the competition jury.

There is no specific date for sending the report, so you can send the report between the beginning and the end of the month.

Monthly updates become mandatory from November 2022.

We are interested in helping you to complete your project as much as possible by the final stage. We wish you success!

Always in touch! Your CopterHack team.

**Comment by okalachev** [comment]
The article file name should be lowercased and end with `.md`. The title of the article should be the name of the project.

**Comment by ssmith-81** [comment]
November update:

Tasks:
1)	Become familiar with the motion capture system from software to hardware. Learn how to set up the motion capture volume, define the coordinate frame for the data to be streamed on along with; calibration, placement of the Optitrack markers on the clover before defining a rigid body and what this data means. Learn the various methods to stream the pose data and most importantly how to get the data to mavros for the PX4.
2)	Implement the newest PX4 firmware 1.13.1 and configure the onboard estimator to work with the motion capture system pose feedback.
3)Validate the Clover is receiving the pose data and the onboard estimator is fusing the external vision pose with the onboard one.
4)	Run some successful test flights (A bit ambitious maybe).
5)	Begin the educational document for Clover users.

Difficulties:
1)	Many of the methods used to extract pose data from the motive software are done using ros packages which do not have the correct architecture to be built on the raspberry Pi. Therefore, another method for transmission must be found.
2)	Difficulties fusing external sensor information with the onboard position estimation. The local position topic (output of ekf) was not producing the same as the vrpn topic which is mapped to the vision_pose/pose topic.
https://dalu-my.sharepoint.com/:v:/g/personal/sn791874_dal_ca/EZWDMQj7wMNFlst2Lr2DWjwBK-mC3wtwvPcHGrD9MP1g1w?email=okalachev%40gmail.com&e=ORdWwF

3)	Unstable flight leading to crashing upon takeoff. When fixed, poor flight in general specifically in x and y (z was fine):
poor_tracking

4)	Timesync errors with mavros along with heartbeat timeout suggesting poor communication between the raspberry Pi and PX4 flight controller
timesync

5)	Difficulties determining and fixing transmission delay(wasn't completely sure if it was an issue), along with ensuring correct timestamping for the external pose data
6)	Possible poor camera readings from the mocap because of the bright lights in the lab reflecting off the clover’s plastic. Many dots that filters tried to filter out.
reflections

Solutions:
1)	Transferring data from the MoCap computer to the raspberry pi required an intermediate system using ubuntu Linux. This allowed me to build a ros package to extract the mocap data (was unable to build vrpn on the raspberry Pi). I used my laptop, which ran a Clover VM and in this system I installed and built a VRPN ROS client package to extract the pose from the mocap/motive software. Transferring it to the Clover was accomplished using a Ros Network where the master ran on the Clover. Remapping the data to the mavos vision_pose topic was accomplished using the ROS topic_tools package that I built within the Clover VM. 
2)	I tried both estimators with various firmware versions. EKF is buggy and doesn’t work with the v1.8.2/Clover specific firmware. The LPE worked a little but many errors would come up such as LPE vision position timeout leading to poor performance or not working at all. Moving to firmware 1.13.0 or 1.13.1 allowed the use of the EKF estimator. Sometimes the data fusion didn’t work but was able to get moderately good flight with this estimator.
3)	Through Rviz I was able to verify that the onboard estimate provided by the EKF was matching the external vision pose provided by the MoCap.
4)	Was able to figure out the mocap setup with both hardware and software. Instability and crashing with the mocap was mainly due to me defining the rigid body/Clover while it was not aligned properly with the Mocaps reference frame. This led to incorrect feedback.
5)	Also, unstable flight was improved by implementing the indirect adaptive controller tuning module provided by PX4. I did this using the mocap where I operated in position mode before starting the module which introduced step inputs to the Clover for rate and attitude controller tuning. I manually tuned the position control module after. An autonomous mission was used in my research, the results can be seen:

XYZ

6)	Timesync errors and timeout errors were minimized by changing the usb connection to UART serial between the raspberry pi and flight controller, errors are not completely removed though.
7)	I spray painted the Clover matte black to eliminate the reflections that may interfere with camera readings (not completely necessary as I have found flight without the paint works just as well, was just in a debugging stage and couldnt find the problem).
8) Stable flight has been accomplished:
https://dalu-my.sharepoint.com/:v:/g/personal/sn791874_dal_ca/EahJeS0Y8LZGgGQa6nNS39oBTx9jUDeW0d9MrTTC5NmOuQ?email=okalachev%40gmail.com&e=oCVLX6

Plans for next month:
1)	I will be away from the lab for most of the month, so I will spend much of my time testing things in gazebo. I am currently working on improving the simple offboard trajectory generation for my research as it requires feedforward velocity, acceleration etc for improved tracking. So, this could be one task.
2)	The next task is the complex trajectory tracking outside of simple offboard where I have the Clover track a figure 8. This is a cool example Clover users can implement to get familiar with coding within the Clover platform as well as outside of the Clover platform. This will give a better understanding of functionalities.
3)	Overall, this month will involve software and autonomous flight programming to provide Clover users with an interesting but not too complicated example for autonomous flight testing within the MoCap.
4)	If I get the chance: One of my Clovers wobbles a small amount during flight so I will adjust the risetime when auto tuning it to find improvement, I will also improve tuning of the position control module.
5)	I will spend more time on the educational document that will allow users to configure the MoCap for the Clover.

**Comment by ssmith-81** [comment]
December update:

Tasks illustrated from last month:
1)	I will be away from the lab for most of the month, so I will spend much of my time testing things in gazebo. I am currently working on improving the simple offboard trajectory generation for my research as it requires feedforward velocity, acceleration etc for improved tracking. So, this could be one task.
2)	The next task is the complex trajectory tracking outside of simple offboard where I have the Clover track a figure 8. This is a cool example Clover users can implement to get familiar with coding within the Clover platform as well as outside of the Clover platform. This will give a better understanding of functionalities.
3)	Overall, this month will involve software and autonomous flight programming to provide Clover users with an interesting but not too complicated example for autonomous flight testing within the MoCap.
4)	If I get the chance: One of my Clovers wobbles a small amount during flight so I will adjust the risetime when auto tuning it to find improvement, I will also improve tuning of the position control module.
5)	I will spend more time on the educational document that will allow users to configure the MoCap for the Clover.


Solutions:
1)	I was able to implement feedforward control with the linear waypoint tracking of the navigate function provided by clover. The results of tracking can be seen:


image

You can see it tracking much closer to the varying trajectory although, because it tracks so closely, the discontinuous velocity of such a trajectory generation leaves the drone having to adjust its velocity very quickly and that is the reason for the overshoot. For a smoother trajectory with smooth velocity will track very well and wont have those sudden changes leading to overshoot. This is seen in the next solution.

2)	I was able to develop the figure 8 trajectory tracking code (working in gazebo). A little snippet can be seen:

image

As you can see, the x-dynamics is generated by a smooth function and it tracks extremely well. Actually, this simulation was conducted under significant wind disturbances (like 10-13 m/s) that is the reason for those small wobbles and it was still able to track extremely well with feedforward. A little code snippet can be seen here:

image

3)	I worked on the educational document, a little snippet of that can be seen:

image

Difficulties:
1)	The main difficulty is transitioning the autonomous flight script to hardware. To take off I use the clover navigate functions, then in order to start the complex trajectory tracking I need to publish through my own script. This requires me to stop/relieve the navigate function. Oleg helped me develop the function to stop it, but, once the publishing stops and switches to the complex trajectory publishing, PX4 does not like that small publishing delay and goes into failsafe mode. So I have to figure out a way to continuously publish even when I stop the navigate function mid flight.

Plans for next month:
1)	I should be back in the lab, so I would like to run some more hardware tests.
2)	Figure out a way to eliminate the setpoint publishing when I stop the navigate publishing mid flight.
3)	Continue to work on the educational document for Clover users.

**Comment by ssmith-81** [comment]
January update
Tasks illustrated from last month:
1)	I should be back in the lab, so I would like to run some more hardware tests.
2)	Figure out a way to eliminate the setpoint publishing when I stop the navigate publishing mid flight.
3)	Continue to work on the educational document for Clover users.

Solutions:
1)	I was able to successfully have the publishing method with Clover simple offboard and MAVROS work on hardware to track a figure 8. An image of the tracking can be seen:
image

It tracked fairly well as you can see. Due to limited space in my mocap volume I had to set a small radius for the figure 8 so when watching it in person it wasn’t completely obvious it was tracking a figure 8 (looked like it was rotating around). I will attach a video as well. Also, I have two Clovers in the lab, one I use for my research and the other I use to test new algorithms and development. Unfortunately, the one I use to test my developments flies very poorly, i.e. it cant maintain a stable altitude at all and tracking x-y references is not ideal. You will notice this in the video as well as in the following altitude tracking:
image
It just continuously bops up and down and cant keep its altitude. I tried tuning the altitude controller with no success. The other clover works very well so the MoCap setup isn’t an issue. I can keep trying to tune better but I haven’t had any success with it.

2)	A video of the figure 8 tracking can be seen:

https://dalu-my.sharepoint.com/:v:/g/personal/sn791874_dal_ca/EYKPIT89dXtNgwoOIhsF3SwBxLeLu8gsqUTGsNQvv-fW4g?e=1d1fBx

It works fine, and with a users Clover that flies well it would be even better. Maybe I can try my Clover that works well and see how it tracks. Also, I converted my SITL simple offboard modules edits that use feedforward tracking to hardware and it works as expected which is nice.

3)	I continued to work on the educational document some. Will create a section to outline the code details and what everything does.

Plans for next month:
1)	I would like to get the small clover working better, will try to retune it using the auto tune module. And then manually tune the position control module from there.
2)	I can create a section in my document that discusses how to use the autotune module with the Clover and MoCap setup, this would be very beneficial for Clover users since manual tuning is not a simple task even for experienced Control engineers (Like myself). So tuning the inner controllers is helpful.
3)	Continue to work on the educational document more.

**Comment by ssmith-81** [comment]
February update
Tasks illustrated from last month:
Plans from last month:
1)	I would like to get the small clover working better, will try to retune it using the auto tune module. And then manually tune the position control module from there.
2)	I can create a section in my document that discusses how to use the autotune module with the Clover and MoCap setup, this would be very beneficial for Clover users since manual tuning is not a simple task even for experienced Control engineers (Like myself). So tuning the inner controllers is helpful.
3)	Continue to work on the educational document more.

Solutions:
1)	I was able to autotune the Clover and record a video as seen in the following:

https://youtu.be/yNZxdxXHKUY


You can see I take off in position mode using the mocap as pose feedback then begin the auto tune process through QGround Control.  While the gains changed a little, I already autotuned it before so there were no major changes. It is mostly the altitude control of this Clover that has trouble, maybe could try adjusting the altitude position and velocity gains... not sure.

Other than the autotune test there, I have been busy in my own research so I tested my nonlinear adaptive robust altitude control system on the Clover and it works great (better then PID) which is nice. Although that isn’t part of this project. I have began documenting the auto tune section in my document as shown:
 
image

This section will give the important steps to setup auto tune with the Clover. Although I use mocap, it can be used with various localizations methods (ArUco markers in position) or (range finder in altitude mode). I did not get as much done this month due to time limitations with research. Although I did work on the document some and will look to do so more.

Plans for next month:
1.	I will look to fine tune the scope of this project. It is basically 3 main components: mocap setup, cool complex trajectory tracking example with feedforward control part, and auto tuning setup example. I feel like I could make many more sections and ideas, although time and work limitations don’t allow this.
2.	Work on the document to put it together in an orderly manner.

**Comment by okalachev** [comment]
@ssmith-81, hi! I edited your article to fix the issues and to make it match the style used in the Clover's documentation, so now the article is almost ready to be merged.

The only issue is used assets sizes. The maximum asset size within the repo is about 300-500KB (as all these files are going to the Clover's image for Raspberry Pi). If you need to use large GIFs or videos, they may be hosted somewhere else, so there should be their full URLs in you repo, for example).

**Comment by okalachev** [comment]
I reduce the size and quality of some of your pictures to meet the requirements, but if you want to keep your original huge logo file, then it should be an external image. 

I guess all the GIFs should be external as they are also huge.

**Comment by ssmith-81** [comment]
I will provide an external source for the images and gifs. Seems all the formatting and things got messed up... will try and fix it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ssmith-81** [comment]
I have all images and gifs as external, however the size still matters as discussed:
"Even if the GIFs were initially uploaded to a third site (e.g. blogspot.com, or giphy.com), they are eventually copied to GitHub servers, and if your GIFs are too big (e.g. more than 5 MB), they will no be shown (only the dreaded error message will be seen)."

Therefore the only solution is to make them smaller or upload them directly to the repository. So I will edit them all to make them smaller tomorrow. Will have it ready by tomorrow

**Comment by ssmith-81** [comment]
> @ssmith-81, hi! I edited your article to fix the issues and to make it match the style used in the Clover's documentation, so now the article is almost ready to be merged.
> 
> The only issue is used assets sizes. The maximum asset size within the repo is about 300-500KB (as all these files are going to the Clover's image for Raspberry Pi). If you need to use large GIFs or videos, they may be hosted somewhere else, so there should be their full URLs in you repo, for example).

All images and gifs are external now with reduced sizes. Let me know if I need to fix anything else.

**Comment by okalachev** [comment]
>"Even if the GIFs were initially uploaded to a third site (e.g. blogspot.com, or giphy.com), they are eventually copied to GitHub servers, and if your GIFs are too big (e.g. more than 5 MB), they will no be shown (only the dreaded error message will be seen)."

There is no problem on hosting big images on GitHub servers, the problem is in images in the repo itself.

But, nevertheless, a 4 MB logo seems an issue from another point of view, I'm not sure making the article reader download so much data is a good idea.

Are you sure you want to keep such a big logo file (and others)? I propose to reduce its (and other images) sizes, like I did in this commit: https://github.com/CopterExpress/clover/pull/470/commits/d6d109afd738b35dbad4bc6e60dc1184e38cac13, and keep GIFs external.

Or you want to keep all the images external? This way, they won't be accessible when viewed from documentation on a Clover.

**Comment by ssmith-81** [comment]
> > "Even if the GIFs were initially uploaded to a third site (e.g. blogspot.com, or giphy.com), they are eventually copied to GitHub servers, and if your GIFs are too big (e.g. more than 5 MB), they will no be shown (only the dreaded error message will be seen)."
> 
> There is no problem on hosting big images on GitHub servers, the problem is in images in the repo itself.
> 
> But, nevertheless, a 4 MB logo seems an issue from another point of view, I'm not sure making the article reader download so much data is a good idea.
> 
> Are you sure you want to keep such a big logo file (and others)? I propose to reduce its (and other images) sizes, like I did in this commit: [d6d109a](https://github.com/CopterExpress/clover/commit/d6d109afd738b35dbad4bc6e60dc1184e38cac13), and keep GIFs external.
> 
> Or you want to keep all the images external? This way, they won't be accessible when viewed from documentation on a Clover.

I removed all of the images and gifs and put them external. I can reduce the images more and put them within the Clover repo if that works better. Just let me known what size is ideal and ill reduce them to that size and put the images within the repo. I will leave the gifs external. Just let me know.

Thanks, Sean

**Comment by ssmith-81** [comment]
> > "Even if the GIFs were initially uploaded to a third site (e.g. blogspot.com, or giphy.com), they are eventually copied to GitHub servers, and if your GIFs are too big (e.g. more than 5 MB), they will no be shown (only the dreaded error message will be seen)."
> 
> There is no problem on hosting big images on GitHub servers, the problem is in images in the repo itself.
> 
> But, nevertheless, a 4 MB logo seems an issue from another point of view, I'm not sure making the article reader download so much data is a good idea.
> 
> Are you sure you want to keep such a big logo file (and others)? I propose to reduce its (and other images) sizes, like I did in this commit: [d6d109a](https://github.com/CopterExpress/clover/commit/d6d109afd738b35dbad4bc6e60dc1184e38cac13), and keep GIFs external.
> 
> Or you want to keep all the images external? This way, they won't be accessible when viewed from documentation on a Clover.

If I leave everything external then they cant be seen at all? I can put the images in the repo and reduce their size, just let me know a good size for the images

**Comment by okalachev** [comment]
There are two images host options:

* The images in the repo, maximum sane size is about 200-400 KB. These images go to the RPi image and accessible from a Clover (it serves the documentation actually) and on the website. This limit is critical, as the overall image size should be below 2 Gb to host in GitHub releases, and we are very close to this limit.
* External images, they only would be accessible when viewed on the website. Maximum size depends, if it's a static logo size, I'd size 1 MB is a max, for GIFs the maximum size is several MBs, but these limits only about making the user not wait too long or not to use much mobile traffic, etc, so these limits are NOT critical.

**Comment by okalachev** [comment]
I would suggest making the logo and diagrams small, like a did in a commit above, and keep all the GIFs external.

**Comment by ssmith-81** [comment]
> I would suggest making the logo and diagrams small, like a did in a commit [above](https://github.com/CopterExpress/clover/commit/d6d109afd738b35dbad4bc6e60dc1184e38cac13), and keep all the GIFs external.

Okay. Everything is external right now, but I will decrease the size of the images <400KB and put them back in the repo. Will do that tomorrow if that is okay

**Comment by ssmith-81** [comment]
> I would suggest making the logo and diagrams small, like a did in a commit [above](https://github.com/CopterExpress/clover/commit/d6d109afd738b35dbad4bc6e60dc1184e38cac13), and keep all the GIFs external.

All images are internal <400kb and all of the gifs are external. Let me know if I need to change anything.

Thanks

**Pull request merged**
