### PR TITLE
Add Generative design frame

### PR DESCRIPTION
**Pull request by danielhonies**
Adds documentation pages about the Aachen Drone Development Initiative's project for the Copterhack 2021 Competition

### CODE REVIEW

**Review by okalachev — CHANGES_REQUESTED** [review]
Hi. Please, note issues, found by markdownlint: https://travis-ci.org/github/CopterExpress/clover/jobs/763002854#L940.

Also, your images are too large. Since all of this data is going to the Clover SD card image, we can't use large images. Please, use online-opmizers or reduce the resolution, to make all of them less than 800 Kb (exceptions are possible, if it's really required).

**Comment by danielhonies** [comment]
Hi, tried to resolve all issues, I think it's ready for merging now 😄

**Comment by okalachev** [comment]
@danielhonies, I made a couple of minor fixes (including optimizing images a little bit more and listing the article in the CopterHack articles list), can you please allow me to push them to your fork, so I can merge all the changes as one commit?

This is done with "Allow edits from maintainers" checkbox: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork.

**Comment by danielhonies** [comment]
@okalachev I dont know why but github doesnt show this option for me. However I have added you as a maintainer to our fork, so you should be able to push to it now.

**Comment by okalachev** [comment]
One last fix. Can you please add a contact link somewhere in the header: e-mail, Telegram, Facebook, whatever.

**Comment by okalachev** [comment]
Thanks!

**Pull request merged**
