### PR TITLE
CopterHack 2023 livesaver

### PR DESCRIPTION
**Pull request by Sarvar00**

### CODE REVIEW

**Comment by SeliverstovaE** [comment]
Dear friend,

Thank you for your interest in the CopterHack 2023 contest. Your application has successfully passed the experts’ review and was accepted for the second project stage of the competition, which will be held until February 28, 2023. This stage will be followed by monthly updates, lectures, and guidance from industry experts.

What's next?

1. Join the Telegram group with participants of the second project stage “[CopterHack 2023, participants chat](https://t.me/+t8hLtf-w2EwzOWM6)”.  
2. Every month, you're expected to prepare free-form reports on the progress of your project (update) in this draft pull request. In your report please indicate your progress, what tasks have been solved. You are encouraged to attach photos and videos that demonstrate the results of the work done within the month.
3. Send the link to the update to the participants chat in the Telegram group.

In response to the message, you will receive feedback from the competition jury.

There is no specific date for sending the report, so you can send the report between the beginning and the end of the month.

Monthly updates become mandatory from November 2022.

We are interested in helping you to complete your project as much as possible by the final stage. We wish you success!

Always in touch! Your CopterHack team.

**Comment by okalachev** [comment]
English article should be in `docs/en` directory.

**Comment by asakeev01** [comment]
# NOVEMBER REPORT
## DONE

- Took pictures and videos near the lake in order to work with these materials, also found images on the internet of a lot of people on the lake.
- Tried to separate water and land with the help of binarizing pictures in Matlab.
- Found the algorithm which can identify the objects and put them in the colored square.

## IN THE PROCESS

- Reading the documentation of the algorithm.
- Trying to identify various cases in the water.
- Brainstorming with the team.

## ISSUES

- No idea how to integrate the drone CPU and camera with the algorithm.

**Comment by Sarvar00** [comment]
DECEMBER REPORT

Planned

- Work on the detection of bodies in the water from photographs.
- Work on the detection of bodies in the water on video.
- Work on the structure that will hold the lifebuoy.
- Work on the mechanism to resetting the lifebuoy.

Completed

- An algorithm was written that recognizes bodies in water on photographs using opencv.
- An algorithm was written that recognizes bodies in water on video using opencv.
- The pieces are 3D printed and glued together to hold the lifebuoy and release it at the right moment.

Next

Work on an algorithm that will calculate the distance between a drone and a person in the water.

**Comment by Sarvar00** [comment]
### JANUARY REPORT



### Planned

- Make an algorithm that will calculate the distance between the camera and the recognized people in meters.
- Display the resulting distance on photos and videos.
- Conduct an experiment, photograph which are 5 meters from the camera and the next person +5 from the first person, and so on.

### Completed

- An algorithm was written that calculates the distance between the camera and people.
- The experiment results are correct below.

-The first person is about 5 meters away from the camera.
image




watgif


-An algorithm that was written to calculate the distance between a camera and people.

`   if FOCAL_LENGTH is None:`
`        FOCAL_LENGTH = ((width * KNOWN_DISTANCE) / (2 * KNOWN_HEIGHT))/2`

`     gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)`

`    faces = face_cascade.detectMultiScale(gray, 1.3, 3)`
`    bodyes = body_cascade.detectMultiScale(gray, 1.3, 3)`
`    for (x, y, w, h) in faces:`
`        face_height = h`
`        distance = ((KNOWN_HEIGHT * FOCAL_LENGTH) / face_height)/2`
`        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 0, 0), 2)`
`        cv2.putText(frame, f"Distance: {distance:.2f} meters", (x, y - 15), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)`
`    for (x, y, w, h) in bodyes:`
`        face_height = h`
`        distance = (KNOWN_HEIGHT * FOCAL_LENGTH) / face_height`
`        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 0, 0), 2)`
`        cv2.putText(frame, f"Distance: {distance:.2f} meters", (x, y - 15), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)`



### Next
-Write an algorithm that will find out at what angle from the drone camera people are standing, swimming.
-Switch to the YOLOV4 or OpenVINO framework

**Pull request closed without merging**
