### PR TITLE
CH2023 - Liceu128 1

### PR DESCRIPTION
**Pull request by Juli-Shvetsova**

### CODE REVIEW

**Comment by SeliverstovaE** [comment]
Dear friend,

Thank you for your interest in the CopterHack 2023 contest. Your application has successfully passed the experts’ review and was accepted for the second project stage of the competition, which will be held until February 28, 2023. This stage will be followed by monthly updates, lectures, and guidance from industry experts.

What's next?

1. Join the Telegram group with participants of the second project stage “[CopterHack 2023, participants chat](https://t.me/+t8hLtf-w2EwzOWM6)”.  
2. Every month, you're expected to prepare free-form reports on the progress of your project (update) in this draft pull request. In your report please indicate your progress, what tasks have been solved. You are encouraged to attach photos and videos that demonstrate the results of the work done within the month.
3. Send the link to the update to the participants chat in the Telegram group.

In response to the message, you will receive feedback from the competition jury.

There is no specific date for sending the report, so you can send the report between the beginning and the end of the month.

Monthly updates become mandatory from November 2022.

We are interested in helping you to complete your project as much as possible by the final stage. We wish you success!

Always in touch! Your CopterHack team.

**Comment by mikemka** [comment]
## November

This month we made a prototype of the charging station




tested it

and started developing the charging station for the "clover" quadcopter.

**Comment by mikemka** [comment]
December.

This month we've done 3d model of charging station and began to cut it according to the drawings from plywood.

Also, we made a client part for a charging station to work with api on wemos d1 (esp8266) and now it is being tested.

We are waiting for the case to be finished and we will be ready to finish developing the firmware for the microcontroller and finishing work with the electronics inside the charging station.

IMG_20221231_192745_929

IMG_20221231_194630_973

**Comment by mikemka** [comment]
January.

This month, we've done the prototype charging station made of plywood on a laser machine

IMG_20230202_100649_447
IMG_20230202_100647_418

and finish API and landing page ([https://qcs.pythonanywhere.com/](https://qcs.pythonanywhere.com/)).

Next month, we are planning to finish the Arduino and ESP8266 software on the station and improve landing at the charging station.

**Comment by mikemka** [comment]
February update.

This month we've done an Arduino and Wemos program that control station. Now, station can connect with API, where are all stations and drones interact. There are 4 step-motors with motors drivers on charging station, LED light. We're using an Arduino to control all them and Wemos to connect with server software.

Also, we've finished design on our website, and created an API connector on drone.

All new media are in gallery page in our website - https://qcs.pythonanywhere.com/gallery/

**Comment by okalachev** [comment]
I edited your article draft a bit so it passes the tests.

**Comment by okalachev** [comment]
@mikemka, is your article done now?

**Comment by mikemka** [comment]
> @mikemka, is your article done now?

sure

**Pull request merged**
