### PR TITLE
Clover Cloud Platform CopterHack 2023

### PR DESCRIPTION
**Pull request by DevMBS**

### CODE REVIEW

**Comment by SeliverstovaE** [comment]
Dear friend,

Thank you for your interest in the CopterHack 2023 contest. Your application has successfully passed the experts’ review and was accepted for the second project stage of the competition, which will be held until February 28, 2023. This stage will be followed by monthly updates, lectures, and guidance from industry experts.

What's next?

1. Join the Telegram group with participants of the second project stage “[CopterHack 2023, participants chat](https://t.me/+t8hLtf-w2EwzOWM6)”.  
2. Every month, you're expected to prepare free-form reports on the progress of your project (update) in this draft pull request. In your report please indicate your progress, what tasks have been solved. You are encouraged to attach photos and videos that demonstrate the results of the work done within the month.
3. Send the link to the update to the participants chat in the Telegram group.

In response to the message, you will receive feedback from the competition jury.

There is no specific date for sending the report, so you can send the report between the beginning and the end of the month.

Monthly updates become mandatory from November 2022.

We are interested in helping you to complete your project as much as possible by the final stage. We wish you success!

Always in touch! Your CopterHack team.

**Comment by DevMBS** [comment]
_#November #CloverCloudTeam_

**During this month we have done:**

- [x] Home Page of the site
- [x] Server processing user requests
- [x] Container management system
- [x] Reception and display of models from the container with gazebo server

We also started making a workspace to work with the simulator (code editor + terminal + simulator).

**Plans for December:**

- [ ] Finalizing the simulator

**Comment by DevMBS** [comment]
_#December #CloverCloudTeam_

This month we have been working to speed up the server’s work, as well as finding and fixing some bugs. We continue to work on the simulation, with plans for the next month to finalize its functionality and start working on the terminal and code editor.

**Comment by DevMBS** [comment]
_#January #CloverCloudTeam_

This month we developed our web terminal with color output and file manager. We have also continued to work on the simulator, and there have been some successes. Attached video - small demonstration of the work of components we worked on this month. Plans for next month include completing the simulator’s functionality, improving the stability of the simulation and making it possible to share workspaces like in CodeSandbox.

**[Workspace demo](https://youtu.be/rrF3M1lNCgs)**

**Comment by DevMBS** [comment]
_#February #CloverCloudTeam_

We are pleased to report that this month we have made some progress in enhancing our code editor and simulator. Additionally, we have started to develop the scene editor that allows for the modification and addition of Aruco markers and other objects. As we work on refining our simulator, we have identified ways to optimize its performance. We will be implementing these optimizations in the coming month. Looking ahead, we have ambitious plans for our workspace exchange system. We aim to complete the scene editor project and begin development on this system soon.

**Comment by okalachev** [comment]
Performed some editing of you article, now it's ready to be merged.

**Pull request merged**
