### PR TITLE
Add Avahi services broadcasting

### PR DESCRIPTION
**Pull request by sfalexrog**
Right now we use Avahi for hostname resolution. This allows us to not worry about DNS misconfigurations and provides name resolution on all interfaces. However, since Avahi does not actually advertise any services on the network, device discovery on the network is still somewhat complicated - you either have to know the hostname beforehand or scan the network using `nmap`. We can do better.

I propose leveraging the Avahi service discovery feature to allow simple drone enumeration on the network without requiring access to a router or performing an `nmap`. The service description files are copied to `/etc/avahi/services` and contain service descriptions, ports, and [other service metadata](https://www.systutorials.com/docs/linux/man/5-avahi.service/).

A host broadcasting its services will be detectable by command-line and GUI applications that enumerate these services (like `avahi-browse` and `avahi-discover` on Ubuntu Linux, `dns-sd` and [Discovery](https://apps.apple.com/us/app/discovery-dns-sd-browser/id1381004916?mt=12) on macOS), as well as other apps that search for a specific exposed service over the network.

### Sample output from `avahi-browse -a`

```
$ avahi-browse -a
+ wlp0s20f3 IPv6 Web interface for clover-6943                 Web Site             local
+ wlp0s20f3 IPv4 Web interface for clever-9167                 Web Site             local
+ wlp0s20f3 IPv4 Web interface for clover-6943                 Web Site             local
+ wlp0s20f3 IPv6 SSH on clever-9167                            SSH Remote Terminal  local
+ wlp0s20f3 IPv6 SSH on clover-6943                            SSH Remote Terminal  local
+ wlp0s20f3 IPv6 clover-6943                                   SSH Remote Terminal  local
+ wlp0s20f3 IPv4 SSH on clever-9167                            SSH Remote Terminal  local
+ wlp0s20f3 IPv4 SSH on clover-6943                            SSH Remote Terminal  local
+ wlp0s20f3 IPv4 clover-6943                                   SSH Remote Terminal  local
```

### Sample output from `avahi-discover`

Screenshot from 2020-05-18 14-13-59

### CODE REVIEW

**Comment by okalachev** [comment]
I'm not against this change though I don't completely get it cause I haven't work with avahi tools much.

The only thing if http or ssh get disabled, then these advertisements would tell the wrong information.

**Comment by okalachev** [comment]
OK, is this change safe enough to merge before releasing 0.20?

**Comment by sfalexrog** [comment]
> The only thing if http or ssh get disabled, then these advertisements would tell the wrong information.

In a perfect world, a service daemon itself performs mDNS broadcasting (like [here, in QGroundControl](https://github.com/mavlink/qgroundcontrol/blob/master/src/comm/UDPLink.cc#L338)). Unfortunately, most daemons tend not to do that. Right now my idea is that SSH is unlikely enough to get disabled.

> OK, is this change safe enough to merge before releasing 0.20?

Seems innocent enough.

**Comment by sfalexrog** [comment]
Looks like exposing sftp-ssh is even better since nautilus (and other file explorers that use gvfs) shows the drone as a network-accessible storage:

Screenshot from 2020-06-03 17-40-48
Screenshot from 2020-06-03 17-51-19

**Comment by okalachev** [comment]
Okay, approve.

**Pull request merged**
